/**
 * Backfill card posters for clips that have none.
 *
 * The library CSV carries no thumbnail column, so every clip loaded from it
 * landed with thumbnail_url NULL and its card renders an empty play-mark —
 * 854 of 1,596 cards. The poster does exist: each clip's source_url is an X
 * post, and X's syndication endpoint (the one its own embeds use, already
 * relied on by src/lib/tweetMedia.ts) returns a poster frame on pbs.twimg.com.
 *
 * This container cannot reach that endpoint — the gateway allowlist denies
 * cdn.syndication.twimg.com — but Postgres can, via the `http` extension. So
 * this emits SQL that carries the per-clip URLs and lets the database do the
 * fetching. The syndication token is a pure function of the status id, so it
 * is computed here and no request is made at build time.
 *
 * Re-runnable: only rows whose thumbnail_url IS NULL are touched, and a clip
 * whose post is deleted or protected simply stays NULL and keeps its
 * play-mark rather than failing the run.
 *
 * Usage: npx tsx scripts/import/build-thumbnail-sql.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { loadSourceLibrary } from '../../pipeline/source';
import { OUT } from './classify';

/** X's syndication token, derived from the status id (same scheme as embeds). */
const syndicationToken = (id: string): string =>
  ((Number(id) / 1e6) * Math.PI).toString(36).replace(/(0+|\.)/g, '');

const statusIdFrom = (url: string): string | null => {
  const m = url.match(/(?:x|twitter)\.com\/[^/]+\/status\/(\d{5,25})/i);
  return m ? m[1] : null;
};

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;

function main() {
  const rows = loadSourceLibrary().filter((r) => !r.prefilter_flag);
  const pairs: string[] = [];
  for (const r of rows) {
    const id = statusIdFrom(r.source_url);
    if (!id) continue;
    const url = `https://cdn.syndication.twimg.com/tweet-result?id=${id}&lang=en&token=${syndicationToken(id)}`;
    pairs.push(`(${q(`APX-C-${r.video_id}`)}, ${q(url)})`);
  }

  const sql = `-- Generated by scripts/import/build-thumbnail-sql.ts — do not hand-edit.
-- Poster source URLs for ${pairs.length} clips. Idempotent.
--
-- A PERMANENT table, not a temporary one: the fetching is done afterwards in
-- bounded batches by public.fill_thumbnails(), because ~850 sequential HTTP
-- calls cannot finish inside one statement. The list has to outlive the
-- session that loads it.
--
-- Internal: no grants are issued, so RLS-less as it is, anon still cannot
-- read it — nothing reaches a client from here.

create table if not exists public.thumb_src (
  clip_id text primary key,
  url     text not null
);

insert into public.thumb_src (clip_id, url) values
${pairs.join(',\n')}
on conflict (clip_id) do nothing;

`;

  fs.mkdirSync(OUT, { recursive: true });
  const out = path.join(OUT, 'thumbnail_backfill.sql');
  fs.writeFileSync(out, sql, 'utf8');
  console.log(`Wrote ${out} — ${pairs.length} clip/URL pairs (${Math.round(sql.length / 1024)} KB)`);
}

main();
