/**
 * Backfill card posters for clips that have none.
 *
 * The library CSV carries no thumbnail column, so every clip loaded from it
 * landed with thumbnail_url NULL and its card renders an empty play-mark —
 * 854 of 1,596 cards. The poster does exist: each clip's source_url is an X
 * post, and X's syndication endpoint (the one its own embeds use, already
 * relied on by src/lib/tweetMedia.ts) returns a poster frame on pbs.twimg.com.
 *
 * This container cannot reach that endpoint — the gateway allowlist denies
 * cdn.syndication.twimg.com — but Postgres can, via the `http` extension. So
 * this emits SQL that carries the per-clip URLs and lets the database do the
 * fetching. The syndication token is a pure function of the status id, so it
 * is computed here and no request is made at build time.
 *
 * Re-runnable: only rows whose thumbnail_url IS NULL are touched, and a clip
 * whose post is deleted or protected simply stays NULL and keeps its
 * play-mark rather than failing the run.
 *
 * Usage: npx tsx scripts/import/build-thumbnail-sql.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { loadSourceLibrary } from '../../pipeline/source';
import { OUT } from './classify';

/** X's syndication token, derived from the status id (same scheme as embeds). */
const syndicationToken = (id: string): string =>
  ((Number(id) / 1e6) * Math.PI).toString(36).replace(/(0+|\.)/g, '');

const statusIdFrom = (url: string): string | null => {
  const m = url.match(/(?:x|twitter)\.com\/[^/]+\/status\/(\d{5,25})/i);
  return m ? m[1] : null;
};

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;

function main() {
  const rows = loadSourceLibrary().filter((r) => !r.prefilter_flag);
  const pairs: string[] = [];
  for (const r of rows) {
    const id = statusIdFrom(r.source_url);
    if (!id) continue;
    const url = `https://cdn.syndication.twimg.com/tweet-result?id=${id}&lang=en&token=${syndicationToken(id)}`;
    pairs.push(`(${q(`APX-C-${r.video_id}`)}, ${q(url)})`);
  }

  const sql = `-- Generated by scripts/import/build-thumbnail-sql.ts — do not hand-edit.
-- Poster backfill for ${pairs.length} clips. Only fills NULLs; safe to re-run.

create temporary table _thumb_src (clip_id text primary key, url text not null) on commit drop;
insert into _thumb_src (clip_id, url) values
${pairs.join(',\n')}
on conflict (clip_id) do nothing;

-- Keep a slow or hanging post from stalling the whole pass.
select extensions.http_set_curlopt('CURLOPT_TIMEOUT', '8');

do $backfill$
declare
  rec    record;
  resp   extensions.http_response;
  poster text;
  ok     int := 0;
  miss   int := 0;
begin
  for rec in
    select t.clip_id, t.url
    from _thumb_src t
    join clips c on c.clip_id = t.clip_id
    where c.thumbnail_url is null
  loop
    begin
      resp := extensions.http_get(rec.url);
      if resp.status = 200 then
        -- The post can hold several media; take the poster of the video one.
        poster := jsonb_path_query_first(
          resp.content::jsonb,
          '$.mediaDetails[*] ? (@.type == "video").media_url_https'
        ) #>> '{}';
        if poster is null then
          poster := jsonb_path_query_first(
            resp.content::jsonb,
            '$.mediaDetails[*].media_url_https'
          ) #>> '{}';
        end if;
      else
        poster := null;
      end if;
    exception when others then
      -- A deleted or protected post is expected, not an error worth aborting
      -- 1,500 rows for. It keeps its play-mark.
      poster := null;
    end;

    if poster is not null then
      update clips set thumbnail_url = poster where clip_id = rec.clip_id;
      ok := ok + 1;
    else
      miss := miss + 1;
    end if;
  end loop;
  raise notice 'posters filled: %, unavailable: %', ok, miss;
end
$backfill$;
`;

  fs.mkdirSync(OUT, { recursive: true });
  const out = path.join(OUT, 'thumbnail_backfill.sql');
  fs.writeFileSync(out, sql, 'utf8');
  console.log(`Wrote ${out} — ${pairs.length} clip/URL pairs (${Math.round(sql.length / 1024)} KB)`);
}

main();
