/**
 * Make card posters for clips whose X post is gone, by pulling a frame from
 * the collection's own copy of the video.
 *
 * 211 clips have no poster: their source post is deleted or protected, so the
 * syndication endpoint returns nothing to fetch. But the awesome-seedance
 * collection publishes MP4s on GitHub Releases for 1,000 of its prompts, and
 * 59 of our blank clips are in that set. For those the video still exists, so
 * a frame can stand in for the missing poster.
 *
 * NOT literally the first frame: films routinely open on a black fade, which
 * would give a black card. ffmpeg's `thumbnail` filter picks the most
 * representative frame out of the opening window instead.
 *
 * LICENCE. These 59 are provably in the CC BY 4.0 collection — their id is a
 * key in its video-urls.json — and we are redistributing a still from their
 * video. So this also sets license/license_url on them, which the library rows
 * could not previously claim. The author credit is already there from the X
 * handle, which is what CC BY requires.
 *
 * Writes public/posters/<video_id>.jpg and out/poster_frames.sql.
 *
 * Usage: npx tsx scripts/import/build-poster-frames.ts <comma-separated ids>
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import ffmpegPath from 'ffmpeg-static';
import { OUT } from './classify';
import { COLLECTION } from './readme-source';

const VIDEO_URLS =
  'https://raw.githubusercontent.com/YouMind-OpenLab/awesome-seedance-2-prompts/main/video-urls.json';

const POSTER_DIR = path.join(process.cwd(), 'public', 'posters');
const TMP = path.join(process.cwd(), 'out', 'tmp-video');

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;

async function main() {
  const arg = process.argv[2];
  if (!arg) throw new Error('pass the blank video_ids, comma separated');
  const wanted = arg.split(',').map((s) => s.trim()).filter(Boolean);

  const res = await fetch(VIDEO_URLS);
  if (!res.ok) throw new Error(`video-urls.json -> ${res.status}`);
  const data = (await res.json()) as { prompts?: Record<string, string> };
  const urls = data.prompts ?? (data as unknown as Record<string, string>);

  fs.mkdirSync(POSTER_DIR, { recursive: true });
  fs.mkdirSync(TMP, { recursive: true });

  const done: string[] = [];
  const failed: string[] = [];

  for (const id of wanted) {
    const url = urls[id];
    if (!url) continue; // no hosted video — nothing to take a frame from
    const mp4 = path.join(TMP, `${id}.mp4`);
    const jpg = path.join(POSTER_DIR, `${id}.jpg`);
    try {
      const r = await fetch(url);
      if (!r.ok) throw new Error(`mp4 ${r.status}`);
      fs.writeFileSync(mp4, Buffer.from(await r.arrayBuffer()));
      execFileSync(
        ffmpegPath as unknown as string,
        [
          '-y', '-loglevel', 'error', '-i', mp4,
          // pick a representative frame from the opening window, not frame 1
          '-vf', 'thumbnail=60,scale=680:-2',
          '-frames:v', '1', '-q:v', '4', jpg,
        ],
        { stdio: 'pipe' },
      );
      if (!fs.existsSync(jpg) || fs.statSync(jpg).size < 1000) throw new Error('empty frame');
      done.push(id);
    } catch (err) {
      failed.push(`${id} (${String(err).slice(0, 60)})`);
    } finally {
      if (fs.existsSync(mp4)) fs.unlinkSync(mp4);
    }
  }

  fs.rmSync(TMP, { recursive: true, force: true });

  const sql = [
    '-- Generated by scripts/import/build-poster-frames.ts — do not hand-edit.',
    `-- ${done.length} posters cut from the collection's own MP4s.`,
    '-- POSTER_BASE is replaced by the caller with the raw URL for the commit',
    '-- that carries these files.',
    '',
    ...done.map(
      (id) =>
        `update clips set thumbnail_url = 'POSTER_BASE/${id}.jpg', ` +
        `license = ${q(COLLECTION.licence)}, license_url = ${q(COLLECTION.licenceUrl)} ` +
        `where clip_id = 'APX-C-${id}' and thumbnail_url is null;`,
    ),
    '',
  ].join('\n');
  fs.writeFileSync(path.join(OUT, 'poster_frames.sql'), sql, 'utf8');

  console.log(`posters written : ${done.length} -> public/posters/`);
  if (failed.length) console.log(`failed          : ${failed.length}\n  ${failed.slice(0, 6).join('\n  ')}`);
  console.log(`sql             : out/poster_frames.sql`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
